# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".husky/**"
      - ".vscode/**"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".husky/**"
      - ".vscode/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  test:
    name: Test 🔧
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required for Chromatic to retrieve git history

      - name: 'notify vercel'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - timjames-dev-next: test'

      - name: Install pnpm ⬇️
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install Node.js ⬇️
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Dependencies ⬇️
        # --ignore-scripts for security
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Check for Vulnerabilities 🔧
        # Don't fail CI if vulnerabilities are found, but still flag them
        run: pnpm audit --production --audit-level=high || echo "Vulnerabilities found"

      - name: Lint 🔧
        run: pnpm --if-present lint

      - name: Check for Unused Dependencies 🔧
        run: pnpm --if-present knip

      - name: Run Unit Tests 🔧
        run: pnpm --if-present test

      - name: Build 🚀
        run: pnpm --if-present build
